<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Lista de estações do INCAPER
        $StationsIncaper = [
            [
                'name' => 'BJNORTE',
                'code' => 'ICP_001_A',
                'description' => '',
                'latitude' => -21.024139,
                'longitude' => -41.585583,
                'altitude' => 631,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 14
            ],
            [
                'name' => 'CACHOEIRO',
                'code' => 'ICP_002_A',
                'description' => '',
                'latitude' => -20.838309,
                'longitude' => -41.139745,
                'altitude' => 345,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 16
            ],
            [
                'name' => 'IUNA',
                'code' => 'ICP_003_A',
                'description' => '',
                'latitude' => -20.355422,
                'longitude' => -41.532613,
                'altitude' => 758,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 38
            ],
            [
                'name' => 'MUCURI',
                'code' => 'ICP_004_A',
                'description' => '',
                'latitude' => -18.107194,
                'longitude' => -40.530611,
                'altitude' => 273,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 50
            ],
            [
                'name' => 'PINHEIROS',
                'code' => 'ICP_005_A',
                'description' => '',
                'latitude' => -18.378944,
                'longitude' => -40.236056,
                'altitude' => 122,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 56
            ],
            [
                'name' => 'SORETAMA',
                'code' => 'ICP_006_A',
                'description' => '',
                'latitude' => -19.114,
                'longitude' => -40.079,
                'altitude' => 75,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 71
            ],
            [
                'name' => 'D_MARTINS',
                'code' => 'ICP_007_A',
                'description' => '',
                'latitude' => -19.114,
                'longitude' => -40.079,
                'altitude' => 950,
                'id_institute' => 1,
                'id_type_station' => 1,
                'id_county' => 23
            ],
        ];

        // Inserindo as estações do INCAPER
        DB::table('stations')->insert($StationsIncaper);

        // Lista de estações do CEPDEC
        $stationsCEPDEC = [
            [
                'name' => 'EMA_ADN_01',
                'code' => 'DEC_001_A',
                'description' => '',
                'latitude' => -18.549833,
                'longitude' => -40.991611,
                'altitude' => 246,
                'operation_begin' => '2022-11-10',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 2
            ],
            [
                'name' => 'EMA_ARN_01',
                'code' => 'DEC_002_A',
                'description' => '',
                'latitude' => -19.059611,
                'longitude' => -41.02825,
                'altitude' => 515,
                'operation_begin' => '2022-10-28',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 6
            ],
            [
                'name' => 'EMA_API_01',
                'code' => 'DEC_003_A',
                'description' => '',
                'latitude' => -21.161833,
                'longitude' => -41.564111,
                'altitude' => 119,
                'operation_begin' => '2022-10-13',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 8
            ],
            [
                'name' => 'EMA_ARA_01',
                'code' => 'DEC_004_A',
                'description' => '',
                'latitude' => -19.797667,
                'longitude' => -40.274972,
                'altitude' => 79,
                'operation_begin' => '2022-07-26',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 9
            ],
            [
                'name' => 'EMA_ATV_01',
                'code' => 'DEC_005_A',
                'description' => '',
                'latitude' => -20.927333,
                'longitude' => -41.185278,
                'altitude' => 70,
                'operation_begin' => '2022-09-21',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 10
            ],
            [
                'name' => 'EMA_CAS_01',
                'code' => 'DEC_006_A',
                'description' => '',
                'latitude' => -20.627528,
                'longitude' => -41.197833,
                'altitude' => 147,
                'operation_begin' => '2022-09-23',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 18
            ],
            [
                'name' => 'EMA_COL_01',
                'code' => 'DEC_007_A',
                'description' => '',
                'latitude' => -19.487111,
                'longitude' => -40.58425,
                'altitude' => 144,
                'operation_begin' => '2022-09-29',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 19
            ],
            [
                'name' => 'EMA_COB_01',
                'code' => 'DEC_008_A',
                'description' => '',
                'latitude' => -18.574806,
                'longitude' => -39.760472,
                'altitude' => 14,
                'operation_begin' => '2022-11-17',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 20
            ],
            [
                'name' => 'EMA_GUC_01',
                'code' => 'DEC_009_A',
                'description' => '',
                'latitude' => -20.772778,
                'longitude' => -41.672167,
                'altitude' => 621,
                'operation_begin' => '2022-10-14',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 28
            ],
            [
                'name' => 'EMA_ICO_01',
                'code' => 'DEC_010_A',
                'description' => '',
                'latitude' => -20.791389,
                'longitude' => -40.794417,
                'altitude' => 69,
                'operation_begin' => '2022-08-12',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 61
            ],
            [
                'name' => 'EMA_ITG_01',
                'code' => 'DEC_011_A',
                'description' => '',
                'latitude' => -19.792667,
                'longitude' => -40.855444,
                'altitude' => 196,
                'operation_begin' => '2022-10-25',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 35
            ],
            [
                'name' => 'EMA_ITP_01',
                'code' => 'DEC_012_A',
                'description' => '',
                'latitude' => -21.032389,
                'longitude' => -40.915694,
                'altitude' => 44,
                'operation_begin' => '2022-09-02',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 36
            ],
            [ 
                'name' => 'EMA_JAG_01',
                'code' => 'DEC_013_A',
                'description' => '',
                'latitude' => -18.9115,
                'longitude' => -40.061444,
                'altitude' => 69,
                'operation_begin' => '2022-07-20',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 39
            ],
            [
                'name' => 'EMA_JON_01',
                'code' => 'DEC_014_A',
                'description' => '',
                'latitude' => -19.768583,
                'longitude' => -40.370833,
                'altitude' => 105,
                'operation_begin' => '2022-07-28',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 41
            ],
            [
                'name' => 'EMA_LAT_01',
                'code' => 'DEC_015_A',
                'description' => '',
                'latitude' => -19.8945,
                'longitude' => -41.054694,
                'altitude' => 259,
                'operation_begin' => '2022-10-20',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 42
            ],
            [
                'name' => 'EMA_MAF_01',
                'code' => 'DEC_016_A',
                'description' => '',
                'latitude' => -20.425667,
                'longitude' => -40.677361,
                'altitude' => 643,
                'operation_begin' => '2022-09-14',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 46
            ],
            [
                'name' => 'EMA_MIS_01',
                'code' => 'DEC_017_A',
                'description' => '',
                'latitude' => -21.065917,
                'longitude' => -41.377972,
                'altitude' => 91,
                'operation_begin' => '2022-10-11',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 48
            ],
            [
                'name' => 'EMA_PAN_01',
                'code' => 'DEC_018_A',
                'description' => '',
                'latitude' => -19.231167,
                'longitude' => -40.829944,
                'altitude' => 125,
                'operation_begin' => '2022-10-27',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 54
            ],
            [
                'name' => 'EMA_PEC_01',
                'code' => 'DEC_019_A',
                'description' => '',
                'latitude' => -18.229581,
                'longitude' => -40.020139,
                'altitude' => 97,
                'operation_begin' => '2022-11-15',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 55
            ],
            [
                'name' => 'EMA_PIU_01',
                'code' => 'DEC_020_A',
                'description' => '',
                'latitude' => -20.831056,
                'longitude' => -40.743389,
                'altitude' => 33,
                'operation_begin' => '2022-08-31',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 57
            ],
            [
                'name' => 'EMA_RIB_01',
                'code' => 'DEC_021_A',
                'description' => '',
                'latitude' => -19.262417,
                'longitude' => -40.337722,
                'altitude' => 126,
                'operation_begin' => '2022-08-24',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 60
            ],
            [
                'name' => 'EMA_SAL_01',
                'code' => 'DEC_022_A',
                'description' => '',
                'latitude' => -20.091333,
                'longitude' => -40.531139,
                'altitude' => 70,
                'operation_begin' => '2022-08-03',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 71
            ],
            [
                'name' => 'EMA_SRC_01',
                'code' => 'DEC_023_A',
                'description' => '',
                'latitude' => -19.729194,
                'longitude' => -40.653528,
                'altitude' => 253,
                'operation_begin' => '2022-10-07',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 69
            ],
            [
                'name' => 'EMA_SER_01',
                'code' => 'DEC_024_A',
                'description' => '',
                'latitude' => -20.19775,
                'longitude' => -40.653528,
                'altitude' => 19,
                'operation_begin' => '2022-07-15',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 70
            ],
            [
                'name' => 'EMA_VAR_01',
                'code' => 'DEC_025_A',
                'description' => '',
                'latitude' => -20.673278,
                'longitude' => -40.99825,
                'altitude' => 662,
                'operation_begin' => '2022-09-16',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 72
            ],
            [
                'name' => 'EMA_VIA_01',
                'code' => 'DEC_026_A',
                'description' => '',
                'latitude' => -20.419444,
                'longitude' => -40.468306,
                'altitude' => 9,
                'operation_begin' => '2022-08-18',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 74
            ],
            [
                'name' => 'EMA_VPA_01',
                'code' => 'DEC_027_A',
                'description' => '',
                'latitude' => -18.607444,
                'longitude' => -40.692056,
                'altitude' => 153,
                'operation_begin' => '2022-11-09',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 75
            ],
            [
                'name' => 'EMA_VVA_01',
                'code' => 'DEC_028_A',
                'description' => '',
                'latitude' => -19.006694,
                'longitude' => -40.383056,
                'altitude' => 178,
                'operation_begin' => '2022-08-26',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 76
            ],
            [
                'name' => 'EMA_VAR_P_01',
                'code' => 'DEC_029_A',
                'description' => '',
                'latitude' => -20.517778,
                'longitude' => -40.988056,
                'altitude' => 1000,
                'operation_begin' => '2022-08-26',
                'id_config_station' => 2,
                'id_institute' => 2,
                'id_type_station' => 1,
                'id_county' => 72,
            ]
        ];

        // Inserindo as estações do CEPDEC
        DB::table('stations')->insert($stationsCEPDEC);

        // Lista de esatações do INMET
        $stationsInmet = [
            [
                'name' => 'A657',
                'code' => 'IMT_001_A',
                'description' => '',
                'latitude' => -20.10416666,
                'longitude' => -41.10694444,
                'altitude' => 507.48,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 1,
            ],
            [
                'name' => 'A617',
                'code' => 'IMT_002_A',
                'description' => '',
                'latitude' => -20.75055555,
                'longitude' => -41.48888888,
                'altitude' => 138,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 4,
            ],
            [
                'name' => 'A615',
                'code' => 'IMT_003_A',
                'description' => '',
                'latitude' => -20.63638888,
                'longitude' => -40.74194444,
                'altitude' => 14.19,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 5,
            ],
            [
                'name' => 'A631',
                'code' => 'IMT_004_A',
                'description' => '',
                'latitude' => -18.29138888,
                'longitude' => -40.73638888,
                'altitude' => 224,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 25,
            ],
            [
                'name' => 'A614',
                'code' => 'IMT_005_A',
                'description' => '',
                'latitude' => -19.35694444,
                'longitude' => -40.0686111,
                'altitude' => 40,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 43,
            ],
            [
                'name' => 'A632',
                'code' => 'IMT_006_A',
                'description' => '',
                'latitude' => -19.40722222,
                'longitude' => -40.53972221,
                'altitude' => 95,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 47,
            ],
            [
                'name' => 'A622',
                'code' => 'IMT_007_A',
                'description' => '',
                'latitude' => -21.10083333,
                'longitude' => -41.03944444,
                'altitude' => 69.12,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 59,
            ],
            [
                'name' => 'A613',
                'code' => 'IMT_008_A',
                'description' => '',
                'latitude' => -19.98833333,
                'longitude' => -40.57944443,
                'altitude' => 975.92,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 64,
            ],
            [
                'name' => 'A616',
                'code' => 'IMT_009_A',
                'description' => '',
                'latitude' => -18.6761111,
                'longitude' => -39.86416666,
                'altitude' => 28.66,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 68,
            ],
            [
                'name' => 'A633',
                'code' => 'IMT_010_A',
                'description' => '',
                'latitude' => -20.38555555,
                'longitude' => -41.18999999,
                'altitude' => 722,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 73,
            ],
            [
                'name' => 'A634',
                'code' => 'IMT_011_A',
                'description' => '',
                'latitude' => -20.46694443,
                'longitude' => -40.40388888,
                'altitude' => 25,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 77,
            ],
            [
                'name' => 'A612',
                'code' => 'IMT_012_A',
                'description' => '',
                'latitude' => -20.27083332,
                'longitude' => -40.30583333,
                'altitude' => 9,
                'id_config_station' => 1,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 78,
            ],
        ];
        
        // Inserindo as estações do INMET
        DB::table('stations')->insert($stationsInmet);

        // Lista de esatações do INMET manuais
        $stationInmetManuals = [
            [
                'name' => '83013',
                'code' => 'IMT_001_M',
                'description' => 'Estação manual de Muniz de Freire',
                'latitude' => -20.46583333,
                'longitude' => -41.41194444,
                'altitude' => 530,
                'automatic' => 0,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 51,
            ],
            [
                'name' => '83648',
                'code' => 'IMT_002_M',
                'description' => 'Estação manual de Vitoria',
                'latitude' => -20.315833,
                'longitude' => -40.316944	,
                'altitude' => 36,
                'automatic' => 0,
                'id_institute' => 3,
                'id_type_station' => 1,
                'id_county' => 78,
            ]
        ];

        // Inserindo as estações do INMET
        DB::table('stations')->insert($stationInmetManuals);

        // Inserindo as estações da ANA
        $stationsAna = [
            [
                'name' => '57739000',
                'code' => 'ANA_001_F',
                'description' => '',
                'latitude' => -20.7725,
                'longitude' => -41.6808,
                'altitude' => null,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 28,
            ],
            [
                'name' => '57562000',
                'code' => 'ANA_002_F',
                'description' => '',
                'latitude' => -20.8744,
                'longitude' => -41.0975,
                'altitude' => 18,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 16,
            ],
            [
                'name' => '57555800',
                'code' => 'ANA_003_F',
                'description' => '',
                'latitude' => -20.8367,
                'longitude' => -41.1203,
                'altitude' => 37,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 16,
            ],
            [
                'name' => '57555500',
                'code' => 'ANA_004_F',
                'description' => '',
                'latitude' => -20.7833,
                'longitude' => -41.1356,
                'altitude' => 43,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 16,
            ],
            [
                'name' => '57119000',
                'code' => 'ANA_005_F',
                'description' => '',
                'latitude' => -20.7833,
                'longitude' => -41.1356,
                'altitude' => 661,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 63,
            ],
            [
                'name' => '56992480',
                'code' => 'ANA_006_F',
                'description' => '',
                'latitude' => -19.5081,
                'longitude' => -40.8369,
                'altitude' => 71,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 19,
            ],
            [
                'name' => '56992400',
                'code' => 'ANA_007_F',
                'description' => '',
                'latitude' => -19.5008,
                'longitude' => -40.9186,
                'altitude' => 71,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 19,
            ],
            [
                'name' => '56992380',
                'code' => 'ANA_008_F',
                'description' => '',
                'latitude' => -19.5328,
                'longitude' => -41.0089,
                'altitude' => 74,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 11,
            ],
            [
                'name' => '56992370',
                'code' => 'ANA_009_F',
                'description' => '',
                'latitude' => -19.6903,
                'longitude' => -41.0267,
                'altitude' => 100,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 11,
            ],
            [
                'name' => '56991380',
                'code' => 'ANA_010_F',
                'description' => '',
                'latitude' => -19.9719,
                'longitude' => -41.1106,
                'altitude' => 275,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 12,
            ],
            [
                'name' => '56991350',
                'code' => 'ANA_011_F',
                'description' => '',
                'latitude' => -19.9689,
                'longitude' => -41.0964,
                'altitude' => 570,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 12,
            ],
            [
                'name' => '56991300',
                'code' => 'ANA_012_F',
                'description' => '',
                'latitude' => -19.9694,
                'longitude' => -41.0678,
                'altitude' => 230,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 42,
            ],
            [
                'name' => '57836000',
                'code' => 'ANA_013_F',
                'description' => '',
                'latitude' => -21.2067,
                'longitude' => -41.3467,
                'altitude' => 15,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 48,
            ],
            [
                'name' => '57774000',
                'code' => 'ANA_014_F',
                'description' => '',
                'latitude' => -21.0936,
                'longitude' => -41.71,
                'altitude' => 163,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 14,
            ],
            [
                'name' => '57769000',
                'code' => 'ANA_015_F',
                'description' => '',
                'latitude' => -21.0164,
                'longitude' => -41.7156,
                'altitude' => 303,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 67,
            ],
            [
                'name' => '57765000',
                'code' => 'ANA_016_F',
                'description' => '',
                'latitude' => -20.9561,
                'longitude' => -41.7175,
                'altitude' => 360,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 67,
            ],
            [
                'name' => '57730000',
                'code' => 'ANA_017_F',
                'description' => '',
                'latitude' => -20.7528,
                'longitude' => -41.8772,
                'altitude' => 660,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 24,
            ],
            [
                'name' => '57435000',
                'code' => 'ANA_018_F',
                'description' => '',
                'latitude' => -20.715,
                'longitude' => -41.5056,
                'altitude' => 123,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57415000',
                'code' => 'ANA_019_F',
                'description' => '',
                'latitude' => -20.4578,
                'longitude' => -41.6753,
                'altitude' => 780,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57410000',
                'code' => 'ANA_020_F',
                'description' => '',
                'latitude' => -20.5861,
                'longitude' => -41.4969,
                'altitude' => 302,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57390000',
                'code' => 'ANA_021_F',
                'description' => '',
                'latitude' => -20.495,
                'longitude' => -41.4858,
                'altitude' => 360,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 51,
            ],
            [
                'name' => '57370005',
                'code' => 'ANA_022_F',
                'description' => '',
                'latitude' => -20.4344,
                'longitude' => -41.5008,
                'altitude' => 598,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 38,
            ],
            [
                'name' => '57256000',
                'code' => 'ANA_023_F',
                'description' => '',
                'latitude' => -20.6097,
                'longitude' => -40.7861,
                'altitude' => 146,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 5,
            ],
            [
                'name' => '57155000',
                'code' => 'ANA_024_F',
                'description' => '',
                'latitude' => -20.3569,
                'longitude' => -40.6275,
                'altitude' => 229,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 23,
            ],
            [
                'name' => '57151000',
                'code' => 'ANA_025_F',
                'description' => '',
                'latitude' => -20.3628,
                'longitude' => -40.64,
                'altitude' => 275,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 23,
            ],
            [
                'name' => '57150500',
                'code' => 'ANA_026_F',
                'description' => '',
                'latitude' => -20.3172,
                'longitude' => -40.6531,
                'altitude' => 455,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 23,
            ],
            [
                'name' => '57830000',
                'code' => 'ANA_027_F',
                'description' => '',
                'latitude' => -21.2061,
                'longitude' => -41.4639,
                'altitude' => 40,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 48,
            ],
            [
                'name' => '57552000',
                'code' => 'ANA_028_F',
                'description' => '',
                'latitude' => -20.7017,
                'longitude' => -41.0894,
                'altitude' => 100,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 16,
            ],
            [
                'name' => '57480000',
                'code' => 'ANA_029_F',
                'description' => '',
                'latitude' => -20.5728,
                'longitude' => -41.2356,
                'altitude' => 100,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 18,
            ],
            [
                'name' => '57474000',
                'code' => 'ANA_030_F',
                'description' => '',
                'latitude' => -20.5728,
                'longitude' => -41.2356,
                'altitude' => 426,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 21,
            ],
            [
                'name' => '57473500',
                'code' => 'ANA_031_F',
                'description' => '',
                'latitude' => -20.4,
                'longitude' => -41.2664,
                'altitude' => 239,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 21,
            ],
            [
                'name' => '57440000',
                'code' => 'ANA_032_F',
                'description' => '',
                'latitude' => -20.7642,
                'longitude' => -41.5233,
                'altitude' => 175,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57430000',
                'code' => 'ANA_033_F',
                'description' => '',
                'latitude' => -20.6739,
                'longitude' => -41.208,
                'altitude' => 220,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57420000',
                'code' => 'ANA_034_F',
                'description' => '',
                'latitude' => -20.5406,
                'longitude' => -41.6656,
                'altitude' => 710,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 32,
            ],
            [
                'name' => '57413000',
                'code' => 'ANA_035_F',
                'description' => '',
                'latitude' => -20.6464,
                'longitude' => -41.4764,
                'altitude' => 201,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 4,
            ],
            [
                'name' => '57370030',
                'code' => 'ANA_036_F',
                'description' => '',
                'latitude' => -20.4675,
                'longitude' => -41.4722,
                'altitude' => 389,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 51,
            ],
            [
                'name' => '57370010',
                'code' => 'ANA_037_F',
                'description' => '',
                'latitude' => -20.4567,
                'longitude' => -41.4792,
                'altitude' => 596,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 51,
            ],
            [
                'name' => '57200000',
                'code' => 'ANA_038_F',
                'description' => '',
                'latitude' => -20.3944,
                'longitude' => -40.5583,
                'altitude' => 51,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 23,
            ],
            [
                'name' => '57120080',
                'code' => 'ANA_039_F',
                'description' => '',
                'latitude' => -20.1019,
                'longitude' => -40.5153,
                'altitude' => 18,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 62,
            ],
            [
                'name' => '57119500',
                'code' => 'ANA_040_F',
                'description' => '',
                'latitude' => -20.0572,
                'longitude' => -40.6175,
                'altitude' => 432,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 63,
            ],
            [
                'name' => '57118080',
                'code' => 'ANA_041_F',
                'description' => '',
                'latitude' => -20.0489,
                'longitude' => -40.4748,
                'altitude' => 643,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 63,
            ],
            [
                'name' => '57117000',
                'code' => 'ANA_042_F',
                'description' => '',
                'latitude' => -20.1139,
                'longitude' => -40.8153,
                'altitude' => 835,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 63,
            ],
            [
                'name' => '56994500',
                'code' => 'ANA_043_F',
                'description' => '',
                'latitude' => -19.5333,
                'longitude' => -40.6297,
                'altitude' => 62,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 19,
            ],
            [
                'name' => '55810000',
                'code' => 'ANA_044_F',
                'description' => '',
                'latitude' => -18.6275,
                'longitude' => -40.1117,
                'altitude' => null,
                'id_institute' => 4,
                'id_type_station' => 4,
                'id_county' => 68,
            ]
        ];

        // Inserindo as estações da AGERH
        DB::table('stations')->insert($stationsAna);
    }
}